#!/bin/bash
# Database and configuration changes for the 5.1.2 update.
#
# No-op: 5.1.2 changed no database schema and no configuration. The only
# configuration-side delta in this release is a reformatting of the dialplan
# contexts generated by setup/installer.php (explanatory comments are no
# longer copied onto the box), and the contexts it generates are functionally
# identical to the ones already on disk - so there is nothing to do here.
#
# An update.sh is mandatory in every patches/<version>/ directory, even a
# no-op like this one: see patches/README.md.

exit 0
